version: "3.8"

services:
  db:
    image: postgres:15-alpine3.17
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - fullstack
    restart: always
  server:
    build: .
    container_name: "backend"
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - fullstack
    depends_on:
      - db

volumes:
  data:

networks:
  fullstack:
    driver: bridge


